[package]
name = "udr"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
reqwest = { version="0.12.5", features=["json"] }
scraper = "0.12.0"

[lib]
crate-type = ["cdylib", "rlib"]